file_format: "1"
id: klotz
name: Klotz
type: shield
url: 
requires: 
  - pro_micro
  - seeeduino_xiao_ble
exposes: 
features:
  - keys
  - encoder
siblings:
  - klotz_left
  - klotz_right
  - klotz_dongle
